### PR TITLE
Fix gradient syntax

### PR DESCRIPTION
**Pull request by K-S-A**
This PR fixes deprecation warning (rails 5 / autoprefixer-rails v6.5):

autoprefixer: ... Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.

### CODE REVIEW

**Comment by jirikolarik** [comment]
Can you provide more descriptions?

**Comment by jirikolarik** [comment]
Thanks for more info. Other then that it's working fine on Rails 5?

**Comment by K-S-A** [comment]
For our project, everything else works great.

**Comment by jirikolarik** [comment]
Thanks!

**Pull request merged**
